import type { LevelCategory } from '@/types/database'

export const UNGROUPED_ASSIGNMENT_NAME = 'ยังไม่จัดกลุ่ม'
export const UNASSESSED_GROUP_NAME = 'ยังไม่ประเมิน'
export const MIXED_ASSIGNMENT_GROUP_NAME = 'กลุ่มผสม'

const LEGACY_AUTO_GROUP_NAMES = new Set([
  'พื้นฐาน / เริ่มต้น',
  'กำลังพัฒนา',
  'กลาง-สูง',
  'ระดับสูง',
])

const DYNAMIC_MEMBER_COUNT_SUFFIX = /\s*\(\s*\d+\s*คน\s*\)\s*$/u
const GENERIC_AUTO_GROUP_NAME = /^กลุ่ม\s+\d+$/u

export interface AssignmentGroupNamingStudent {
  level: number | null
  levelCategory: LevelCategory | null
  levelProgramName: string | null
}

export type AutoGroupNameError =
  | 'no_members'
  | 'incomplete_level_definition'
  | 'mixed_level_categories'

export interface AutoGroupNameResult {
  name: string | null
  error: AutoGroupNameError | null
  levelMin: number | null
  levelMax: number | null
}

export function stripDynamicMemberCount(name: string | null | undefined) {
  return (name || '').replace(DYNAMIC_MEMBER_COUNT_SUFFIX, '').trim()
}

export function isAutoGeneratedAssignmentGroupName(name: string | null | undefined) {
  const value = (name || '').trim()
  if (!value || value === UNGROUPED_ASSIGNMENT_NAME) return true
  if (DYNAMIC_MEMBER_COUNT_SUFFIX.test(value)) return true
  if (GENERIC_AUTO_GROUP_NAME.test(value)) return true
  return LEGACY_AUTO_GROUP_NAMES.has(value)
}

export function deriveAssignmentGroupAutoName(
  students: AssignmentGroupNamingStudent[],
): AutoGroupNameResult {
  if (students.length === 0) {
    return { name: null, error: 'no_members', levelMin: null, levelMax: null }
  }

  const levels = students.map((student) => student.level ?? 0)
  const levelMin = Math.min(...levels)
  const levelMax = Math.max(...levels)
  const assessed = students.filter((student) => (student.level ?? 0) > 0)

  if (assessed.length === 0) {
    return {
      name: UNASSESSED_GROUP_NAME,
      error: null,
      levelMin,
      levelMax,
    }
  }

  if (assessed.length !== students.length) {
    return { name: null, error: 'mixed_level_categories', levelMin, levelMax }
  }

  if (assessed.some((student) => !student.levelCategory || !student.levelProgramName?.trim())) {
    return { name: null, error: 'incomplete_level_definition', levelMin, levelMax }
  }

  const categoryKeys = new Set(assessed.map((student) => student.levelCategory))
  const programNames = new Set(assessed.map((student) => student.levelProgramName?.trim()))
  if (categoryKeys.size !== 1 || programNames.size !== 1) {
    return { name: null, error: 'mixed_level_categories', levelMin, levelMax }
  }

  return {
    name: Array.from(programNames)[0] || null,
    error: null,
    levelMin,
    levelMax,
  }
}

export function resolveAssignmentGroupName({
  currentName,
  students,
}: {
  currentName: string | null | undefined
  students: AssignmentGroupNamingStudent[]
}) {
  const value = (currentName || '').trim()
  if (!isAutoGeneratedAssignmentGroupName(value)) {
    return {
      name: value,
      autoNamed: false,
      error: null as AutoGroupNameError | null,
      levelMin: null as number | null,
      levelMax: null as number | null,
    }
  }

  const derived = deriveAssignmentGroupAutoName(students)
  return {
    ...derived,
    autoNamed: Boolean(derived.name),
  }
}

function getAssignmentGroupLevelRange(students: AssignmentGroupNamingStudent[]) {
  if (students.length === 0) return { levelMin: null, levelMax: null }
  const levels = students.map((student) => student.level ?? 0)
  return {
    levelMin: Math.min(...levels),
    levelMax: Math.max(...levels),
  }
}

function isCoachAutoNamePlaceholder(name: string) {
  return !name || name === UNGROUPED_ASSIGNMENT_NAME || GENERIC_AUTO_GROUP_NAME.test(name)
}

export function getCoachAssignmentLevelWarning(
  students: AssignmentGroupNamingStudent[],
): Extract<AutoGroupNameError, 'incomplete_level_definition' | 'mixed_level_categories'> | null {
  const error = deriveAssignmentGroupAutoName(students).error
  if (error === 'incomplete_level_definition' || error === 'mixed_level_categories') return error
  return null
}

export function resolveCoachAssignmentGroupName({
  currentName,
  students,
}: {
  currentName: string | null | undefined
  students: AssignmentGroupNamingStudent[]
}) {
  const value = stripDynamicMemberCount(currentName)
  const levelRange = getAssignmentGroupLevelRange(students)

  if (!isCoachAutoNamePlaceholder(value)) {
    return {
      name: value,
      autoNamed: false,
      error: null as AutoGroupNameError | null,
      ...levelRange,
    }
  }

  const derived = deriveAssignmentGroupAutoName(students)
  if (derived.error === 'incomplete_level_definition' || derived.error === 'mixed_level_categories') {
    return {
      name: MIXED_ASSIGNMENT_GROUP_NAME,
      autoNamed: true,
      error: null as AutoGroupNameError | null,
      levelMin: derived.levelMin,
      levelMax: derived.levelMax,
    }
  }

  return {
    ...derived,
    autoNamed: Boolean(derived.name),
  }
}

export function formatAutoGroupNameError(error: AutoGroupNameError) {
  if (error === 'no_members') return 'ต้องมีผู้เรียนในกลุ่มก่อนตั้งชื่ออัตโนมัติ'
  if (error === 'incomplete_level_definition') {
    return 'ข้อมูล Level ของผู้เรียนไม่ครบหรือไม่อยู่ใน Level ที่เปิดใช้งาน กรุณาตรวจข้อมูลหรือตั้งชื่อกลุ่มเอง'
  }
  return 'ผู้เรียนอยู่คนละหมวด Level และยังไม่มีกฎชื่อรวม กรุณาตั้งชื่อกลุ่มเองหรือใช้ “จัดตาม Level”'
}
